language: python

python:
    - 2.7
    - 3.4
    - 3.5

env:
    - NUMPY_VERSION=1.10 OMP_NUM_THREADS=2

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose
    - python setup.py install

script:
    - python ./runtests.py

deploy:
    - provider : pypi
      distributions: sdist
      user: "rainwoodman"
      password:
        secure: "mLc44GMDP3O74jFo3gxsdBb35gtq0evmNK699S7WGwcrFMTeFu78xNf+0p5hANtjG86XyLDvAk5i4+G8JmNeXox7u+T5+VHo75Z3Y7VB6wLsvCIxbraPY33p2jEtcJMeRHT3D6GVw0JB1ZaxO1PKVsO1SfUGGg0GBhPRDBZNkUTWIcZG7Fb3HFCQ4o71ZcrdDrZNhoM5bJhDEvTheGXHRyrMuqAeyX7yD6sbq/XPKKoPP7FOdl663TZgbuCvRo/jYumv/cqEdws5kRBqmyJPfDM7GvKQjmPVb945HXQFfJZxoQ48mQLoWU6Fn8rdo2JzHwW6qawp+UTcsIJ38qwWQ6Almz+UzR9poc818EzblMnHxfUfPQlv6O65VdM4Wsb4WxSFfcPdQekQkBovTzWs4IhMZpHkxrsMiHDMMgIYIMznQAvPzC6Vl6rUaSVbBuv3JyZvi63WeQoN1vhSxlfelKTskAKYKx2rouzvFHP2Dw3UEjTHE1DRM1dipRVibD55tgnET8z5A1szvDO9/88DGl4hTm7nX4vpX8gV8UCCU5PwDxZCEogL5/8ckEa66ZGTc01BtazQfJtGQABBByil5zyYLog0NiXElKRTWR22QgIhURB5/uO5XVbbyfiR6kDeRpMcblX0sx42XbXmQ+dzzx9trTKorTbZdSoBVCmxQ94="
      on:
        tags : true
        condition : ${TRAVIS_JOB_NUMBER##*.} == 1
